[package]
name = "verovior"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
cmake = "0.1"
bindgen = "0.72"